env:
  browser: true
  jquery: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 5
  sourceType: script
  impliedStrict: true
  jsx: false
rules:
  comma-dangle:
    - error
    - "never"
  no-plusplus:
    - error
    - {allowForLoopAfterthoughts: true}
  no-var: off
  object-shorthand: off
  prefer-arrow-callback: off
  prefer-const: off
  prefer-destructuring: off
  prefer-numeric-literals: off
  prefer-rest-params: off
  prefer-spread: off
  prefer-template: off
  vars-on-top: off
