env:
  browser: true
  jquery: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 5
  sourceType: script
  impliedStrict: true
  jsx: false
rules: {}
